"""
PFAA Generated Tools — Auto-generated by the self-builder.

These tools were created by the PFAA engine analyzing its own needs
and using Claude to generate implementations. Each tool was:
    1. Proposed based on self-analysis
    2. Generated by Claude following PFAA patterns
    3. Sandbox-tested for compilation and basic execution
    4. Appended to this file

Python 3.15: Uses lazy imports throughout.
"""

from __future__ import annotations

lazy import json

from agent_setup_cli.core.phase import Phase
from agent_setup_cli.core.tools import ToolSpec, registry


@registry.register(ToolSpec(
    name="codebase_search",
    description="Search codebase for patterns with context",
    phase=Phase.LIQUID,
    capabilities=("search", "read"),
))
def tool_codebase_search(
    pattern: str,
    root: str = ".",
    context_lines: int = 2,
    file_glob: str = "*.py",
) -> dict:
    import re, os as _os
    import glob as glob_mod
    compiled = re.compile(pattern)
    results, files_searched = [], 0
    for fp in glob_mod.glob(_os.path.join(root, "**", file_glob), recursive=True):
        if not _os.path.isfile(fp): continue
        if any(s in fp for s in ["venv","__pycache__",".git"]): continue
        files_searched += 1
        try:
            with open(fp) as f: lines = f.readlines()
            for i, line in enumerate(lines):
                if compiled.search(line):
                    s, e = max(0, i-context_lines), min(len(lines), i+context_lines+1)
                    results.append({"file":fp,"line":i+1,"match":line.rstrip(),"context":[l.rstrip() for l in lines[s:e]]})
        except (UnicodeDecodeError, PermissionError): continue
    return {"success":True,"pattern":pattern,"files_searched":files_searched,"total_matches":len(results),"results":results[:50]}

